# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VendRoute' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for VendRoute
  pod 'iOS-Slide-Menu'
  pod 'CalendarFoundation'
  pod 'Amplify'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
end
